export enum Categories {
	OTHERS = 'others',
	HOUSEHOLD = 'household',
	OFFICE = 'office',
	ELETRONICS = 'eletronics',
	CLOTHING = 'clothing',
	MUSIC = 'music',
	GAMES = 'games',
	SPORTS = 'sports',
	DISHWARE = 'dishware',
	DRINKS = 'drinks',
	FOOD_SWEET = 'food_sweet',
	FOOD_MARINE = 'food_marine',
	FOOD_ASIAN = 'food_asian',
	FOOD_PREPARED = 'food_prepared',
	VEGETABLES = 'vegetables',
	FRUITS = 'fruits',
}
