export enum Categories {
	OTHERS = 'others',
	HOUSEHOLD = 'household',
	OFFICE = 'office',
	ELETRONICS = 'eletronics',
	CLOTHING = 'clothing',
	MUSIC = 'music',
	GAMES = 'games',
	SPORTS = 'sports',
	DISHWARE = 'dishware',
	DRINKS = 'drinks',
	SWEET = 'sweet',
	FOOD = 'food',
	VEGETABLES = 'vegetables',
	FRUITS = 'fruits',
}
